problem: missing metrics method in rawdb
core/rawdb/schema.go:62:23: undefined: github.com/ethereumproject/go-ethereum/metrics.NewRegisteredCounter

solution: steal ef/metrics